# Generated by Django 3.2.9 on 2021-12-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categroy',
            new_name='category',
        ),
    ]
